services:
  frontend:
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://backend:8080
      - NEXT_PUBLIC_DOCKER=true
    image: 3900-githappens-frontend
    build:
      context: ./frontend
      target: dev
    restart: unless-stopped
    networks:
      - 3900-network
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    working_dir: /app
    command: pnpm run dev
  backend:
    image: 3900-githappens-backend
    build:
      context: ./backend
      target: dev
    restart: unless-stopped
    networks:
      - 3900-network
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
      - /app/node_modules
    working_dir: /app
    command: pnpm run dev
networks:
  3900-network:
    driver: bridge
