services:
  frontend:
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://backend:8080
      - NEXT_PUBLIC_DOCKER=true
    image: 3900-githappens-frontend
    build:
      context: ./frontend
    restart: unless-stopped
    networks:
      - 3900-network
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - mongodb
  backend:
    image: 3900-githappens-backend
    build:
      context: ./backend
    restart: unless-stopped
    environment:
      - USE_LOCAL_MONGO=true
      - USE_DOCKER_INTERNAL_MONGO=true
    networks:
      - 3900-network
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    expose:
      - "27017"
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_container:/data/db
    networks:
      - 3900-network
    logging:
      driver: none
networks:
  3900-network:
    driver: bridge
volumes:
  mongodb_data_container:
