branch-defaults:
  default:
    environment: githappens-backend
environment-defaults:
  githappens-backend:
    branch: null
    repository: null
global:
  application_name: alvin-webserver
  default_ec2_keyname: null
  default_platform: Node.js 16 running on 64bit Amazon Linux 2
  default_region: ap-southeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: null
  workspace_type: Application
