branch-defaults:
  default:
    environment: Cs3900-githappens-be-env
environment-defaults:
  Cs3900-githappens-be-env:
    branch: null
    repository: null
global:
  application_name: cs3900-githappens-be
  default_ec2_keyname: null
  default_platform: Node.js 16 running on 64bit Amazon Linux 2
  default_region: ap-southeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: null
  workspace_type: Application
